// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class UploadTaskPigeonCodecReader: FlutterStandardReader {
}

private class UploadTaskPigeonCodecWriter: FlutterStandardWriter {
}

private class UploadTaskPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UploadTaskPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UploadTaskPigeonCodecWriter(data: data)
  }
}

class UploadTaskPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = UploadTaskPigeonCodec(readerWriter: UploadTaskPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UploadApi {
  func createUploadTask(accessToken: String, checksum: String, cloudId: String?, deviceId: String, group: String, livePhotoVideoId: String?, localId: String, url: String, completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UploadApiSetup {
  static var codec: FlutterStandardMessageCodec { UploadTaskPigeonCodec.shared }
  /// Sets up an instance of `UploadApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UploadApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createUploadTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.UploadApi.createUploadTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createUploadTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessTokenArg = args[0] as! String
        let checksumArg = args[1] as! String
        let cloudIdArg: String? = nilOrValue(args[2])
        let deviceIdArg = args[3] as! String
        let groupArg = args[4] as! String
        let livePhotoVideoIdArg: String? = nilOrValue(args[5])
        let localIdArg = args[6] as! String
        let urlArg = args[7] as! String
        api.createUploadTask(accessToken: accessTokenArg, checksum: checksumArg, cloudId: cloudIdArg, deviceId: deviceIdArg, group: groupArg, livePhotoVideoId: livePhotoVideoIdArg, localId: localIdArg, url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createUploadTaskChannel.setMessageHandler(nil)
    }
  }
}
